language: android
jdk: oraclejdk7
#env:
#  matrix:
#    - ANDROID_TARGET=android-22

android:
  components:
    - build-tools-22.0.1
    - android-22
  licenses:
    - 'android-sdk-license-.+'


before_script:
  # Create and start emulator
  # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - adb wait-for-device
  # - adb shell input keyevent 82 &

script:
  # - ./gradlew connectedAndroidTest
  - ./gradlew assembleDebug
  # - ./gradlew installDebug --stacktrace
cache:
  directories:
    - $HOME/.gradle
